export { default as Home } from "./Home/Home";
export { default as Fashion } from "./Fashion/Fashion";
export { default as ContactUs } from "./ContactUs/ContactUs";
export { default as Favorite } from "./Favorite/Favorite";
export { default as Login } from "./Login/Login";
export { default as Register } from "./Register/Register";
export { default as NewClothes } from "./Catalogue-Clothes/NewClothes/NewClothes";
export { default as AllClothes } from "./Catalogue-Clothes/All Clothes/AllClothes";
export { default as OneClothes } from "./Catalogue-Clothes/Get One Clothes/OneClothes";
export { default as AllBuyedClothes } from "./Catalogue-Clothes/AllBuyedClothes/AllBuyedClothes";
export { default as Dashboard } from "./Dashboard/Main-Dashbord/Dashboard";
export { default as UsersPage } from "./Dashboard/Users-Page/UsersPage";
export { default as OneUserPage } from "./Dashboard/Users-Page/OneUserPage/OneUserPage";
export { default as CountContainer } from "./Catalogue-Clothes/CountContainer/CountContainer";
export { default as MessagesPage } from "./ContactUs/AllMessages/All-Messages";
